#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KHO.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLKho")]
	public partial class DbQLKhoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCTPhieuNhap(CTPhieuNhap instance);
    partial void UpdateCTPhieuNhap(CTPhieuNhap instance);
    partial void DeleteCTPhieuNhap(CTPhieuNhap instance);
    partial void InsertCTPhieuXuat(CTPhieuXuat instance);
    partial void UpdateCTPhieuXuat(CTPhieuXuat instance);
    partial void DeleteCTPhieuXuat(CTPhieuXuat instance);
    partial void InsertDangnhap(Dangnhap instance);
    partial void UpdateDangnhap(Dangnhap instance);
    partial void DeleteDangnhap(Dangnhap instance);
    partial void InsertKho(Kho instance);
    partial void UpdateKho(Kho instance);
    partial void DeleteKho(Kho instance);
    partial void InsertDiaDiem(DiaDiem instance);
    partial void UpdateDiaDiem(DiaDiem instance);
    partial void DeleteDiaDiem(DiaDiem instance);
    partial void InsertLoaiHang(LoaiHang instance);
    partial void UpdateLoaiHang(LoaiHang instance);
    partial void DeleteLoaiHang(LoaiHang instance);
    partial void InsertPhieuNhap(PhieuNhap instance);
    partial void UpdatePhieuNhap(PhieuNhap instance);
    partial void DeletePhieuNhap(PhieuNhap instance);
    partial void InsertPhieuXuat(PhieuXuat instance);
    partial void UpdatePhieuXuat(PhieuXuat instance);
    partial void DeletePhieuXuat(PhieuXuat instance);
    partial void InsertMatHang(MatHang instance);
    partial void UpdateMatHang(MatHang instance);
    partial void DeleteMatHang(MatHang instance);
    #endregion
		
		public DbQLKhoDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QLKhoConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DbQLKhoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbQLKhoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbQLKhoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbQLKhoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CTPhieuNhap> CTPhieuNhaps
		{
			get
			{
				return this.GetTable<CTPhieuNhap>();
			}
		}
		
		public System.Data.Linq.Table<CTPhieuXuat> CTPhieuXuats
		{
			get
			{
				return this.GetTable<CTPhieuXuat>();
			}
		}
		
		public System.Data.Linq.Table<Dangnhap> Dangnhaps
		{
			get
			{
				return this.GetTable<Dangnhap>();
			}
		}
		
		public System.Data.Linq.Table<Kho> Khos
		{
			get
			{
				return this.GetTable<Kho>();
			}
		}
		
		public System.Data.Linq.Table<DiaDiem> DiaDiems
		{
			get
			{
				return this.GetTable<DiaDiem>();
			}
		}
		
		public System.Data.Linq.Table<LoaiHang> LoaiHangs
		{
			get
			{
				return this.GetTable<LoaiHang>();
			}
		}
		
		public System.Data.Linq.Table<PhieuNhap> PhieuNhaps
		{
			get
			{
				return this.GetTable<PhieuNhap>();
			}
		}
		
		public System.Data.Linq.Table<PhieuXuat> PhieuXuats
		{
			get
			{
				return this.GetTable<PhieuXuat>();
			}
		}
		
		public System.Data.Linq.Table<MatHang> MatHangs
		{
			get
			{
				return this.GetTable<MatHang>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTPhieuNhap")]
	public partial class CTPhieuNhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SOPN;
		
		private string _MaMH;
		
		private string _TenMH;
		
		private string _LoaiHang;
		
		private int _DonGia;
		
		private int _SoLuong;
		
		private EntityRef<LoaiHang> _LoaiHang1;
		
		private EntityRef<PhieuNhap> _PhieuNhap;
		
		private EntityRef<MatHang> _MatHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSOPNChanging(string value);
    partial void OnSOPNChanged();
    partial void OnMaMHChanging(string value);
    partial void OnMaMHChanged();
    partial void OnTenMHChanging(string value);
    partial void OnTenMHChanged();
    partial void OnLoaiHangChanging(string value);
    partial void OnLoaiHangChanged();
    partial void OnDonGiaChanging(int value);
    partial void OnDonGiaChanged();
    partial void OnSoLuongChanging(int value);
    partial void OnSoLuongChanged();
    #endregion
		
		public CTPhieuNhap()
		{
			this._LoaiHang1 = default(EntityRef<LoaiHang>);
			this._PhieuNhap = default(EntityRef<PhieuNhap>);
			this._MatHang = default(EntityRef<MatHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOPN", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SOPN
		{
			get
			{
				return this._SOPN;
			}
			set
			{
				if ((this._SOPN != value))
				{
					if (this._PhieuNhap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSOPNChanging(value);
					this.SendPropertyChanging();
					this._SOPN = value;
					this.SendPropertyChanged("SOPN");
					this.OnSOPNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMH", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaMH
		{
			get
			{
				return this._MaMH;
			}
			set
			{
				if ((this._MaMH != value))
				{
					if (this._MatHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaMHChanging(value);
					this.SendPropertyChanging();
					this._MaMH = value;
					this.SendPropertyChanged("MaMH");
					this.OnMaMHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMH", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenMH
		{
			get
			{
				return this._TenMH;
			}
			set
			{
				if ((this._TenMH != value))
				{
					this.OnTenMHChanging(value);
					this.SendPropertyChanging();
					this._TenMH = value;
					this.SendPropertyChanged("TenMH");
					this.OnTenMHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiHang", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string LoaiHang
		{
			get
			{
				return this._LoaiHang;
			}
			set
			{
				if ((this._LoaiHang != value))
				{
					if (this._LoaiHang1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLoaiHangChanging(value);
					this.SendPropertyChanging();
					this._LoaiHang = value;
					this.SendPropertyChanged("LoaiHang");
					this.OnLoaiHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Int NOT NULL")]
		public int DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int NOT NULL")]
		public int SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiHang_CTPhieuNhap", Storage="_LoaiHang1", ThisKey="LoaiHang", OtherKey="MSLH", IsForeignKey=true)]
		public LoaiHang LoaiHang1
		{
			get
			{
				return this._LoaiHang1.Entity;
			}
			set
			{
				LoaiHang previousValue = this._LoaiHang1.Entity;
				if (((previousValue != value) 
							|| (this._LoaiHang1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiHang1.Entity = null;
						previousValue.CTPhieuNhaps.Remove(this);
					}
					this._LoaiHang1.Entity = value;
					if ((value != null))
					{
						value.CTPhieuNhaps.Add(this);
						this._LoaiHang = value.MSLH;
					}
					else
					{
						this._LoaiHang = default(string);
					}
					this.SendPropertyChanged("LoaiHang1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuNhap_CTPhieuNhap", Storage="_PhieuNhap", ThisKey="SOPN", OtherKey="SOPN", IsForeignKey=true)]
		public PhieuNhap PhieuNhap
		{
			get
			{
				return this._PhieuNhap.Entity;
			}
			set
			{
				PhieuNhap previousValue = this._PhieuNhap.Entity;
				if (((previousValue != value) 
							|| (this._PhieuNhap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhieuNhap.Entity = null;
						previousValue.CTPhieuNhaps.Remove(this);
					}
					this._PhieuNhap.Entity = value;
					if ((value != null))
					{
						value.CTPhieuNhaps.Add(this);
						this._SOPN = value.SOPN;
					}
					else
					{
						this._SOPN = default(string);
					}
					this.SendPropertyChanged("PhieuNhap");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MatHang_CTPhieuNhap", Storage="_MatHang", ThisKey="MaMH", OtherKey="MaMH", IsForeignKey=true)]
		public MatHang MatHang
		{
			get
			{
				return this._MatHang.Entity;
			}
			set
			{
				MatHang previousValue = this._MatHang.Entity;
				if (((previousValue != value) 
							|| (this._MatHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MatHang.Entity = null;
						previousValue.CTPhieuNhaps.Remove(this);
					}
					this._MatHang.Entity = value;
					if ((value != null))
					{
						value.CTPhieuNhaps.Add(this);
						this._MaMH = value.MaMH;
					}
					else
					{
						this._MaMH = default(string);
					}
					this.SendPropertyChanged("MatHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTPhieuXuat")]
	public partial class CTPhieuXuat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SOPX;
		
		private string _MaMH;
		
		private string _TenMH;
		
		private string _LoaiHang;
		
		private int _DonGia;
		
		private int _SoLuong;
		
		private EntityRef<LoaiHang> _LoaiHang1;
		
		private EntityRef<PhieuNhap> _PhieuNhap;
		
		private EntityRef<MatHang> _MatHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSOPXChanging(string value);
    partial void OnSOPXChanged();
    partial void OnMaMHChanging(string value);
    partial void OnMaMHChanged();
    partial void OnTenMHChanging(string value);
    partial void OnTenMHChanged();
    partial void OnLoaiHangChanging(string value);
    partial void OnLoaiHangChanged();
    partial void OnDonGiaChanging(int value);
    partial void OnDonGiaChanged();
    partial void OnSoLuongChanging(int value);
    partial void OnSoLuongChanged();
    #endregion
		
		public CTPhieuXuat()
		{
			this._LoaiHang1 = default(EntityRef<LoaiHang>);
			this._PhieuNhap = default(EntityRef<PhieuNhap>);
			this._MatHang = default(EntityRef<MatHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOPX", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SOPX
		{
			get
			{
				return this._SOPX;
			}
			set
			{
				if ((this._SOPX != value))
				{
					if (this._PhieuNhap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSOPXChanging(value);
					this.SendPropertyChanging();
					this._SOPX = value;
					this.SendPropertyChanged("SOPX");
					this.OnSOPXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMH", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaMH
		{
			get
			{
				return this._MaMH;
			}
			set
			{
				if ((this._MaMH != value))
				{
					if (this._MatHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaMHChanging(value);
					this.SendPropertyChanging();
					this._MaMH = value;
					this.SendPropertyChanged("MaMH");
					this.OnMaMHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMH", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenMH
		{
			get
			{
				return this._TenMH;
			}
			set
			{
				if ((this._TenMH != value))
				{
					this.OnTenMHChanging(value);
					this.SendPropertyChanging();
					this._TenMH = value;
					this.SendPropertyChanged("TenMH");
					this.OnTenMHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiHang", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string LoaiHang
		{
			get
			{
				return this._LoaiHang;
			}
			set
			{
				if ((this._LoaiHang != value))
				{
					if (this._LoaiHang1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLoaiHangChanging(value);
					this.SendPropertyChanging();
					this._LoaiHang = value;
					this.SendPropertyChanged("LoaiHang");
					this.OnLoaiHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Int NOT NULL")]
		public int DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int NOT NULL")]
		public int SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiHang_CTPhieuXuat", Storage="_LoaiHang1", ThisKey="LoaiHang", OtherKey="MSLH", IsForeignKey=true)]
		public LoaiHang LoaiHang1
		{
			get
			{
				return this._LoaiHang1.Entity;
			}
			set
			{
				LoaiHang previousValue = this._LoaiHang1.Entity;
				if (((previousValue != value) 
							|| (this._LoaiHang1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiHang1.Entity = null;
						previousValue.CTPhieuXuats.Remove(this);
					}
					this._LoaiHang1.Entity = value;
					if ((value != null))
					{
						value.CTPhieuXuats.Add(this);
						this._LoaiHang = value.MSLH;
					}
					else
					{
						this._LoaiHang = default(string);
					}
					this.SendPropertyChanged("LoaiHang1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuNhap_CTPhieuXuat", Storage="_PhieuNhap", ThisKey="SOPX", OtherKey="SOPN", IsForeignKey=true)]
		public PhieuNhap PhieuNhap
		{
			get
			{
				return this._PhieuNhap.Entity;
			}
			set
			{
				PhieuNhap previousValue = this._PhieuNhap.Entity;
				if (((previousValue != value) 
							|| (this._PhieuNhap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhieuNhap.Entity = null;
						previousValue.CTPhieuXuats.Remove(this);
					}
					this._PhieuNhap.Entity = value;
					if ((value != null))
					{
						value.CTPhieuXuats.Add(this);
						this._SOPX = value.SOPN;
					}
					else
					{
						this._SOPX = default(string);
					}
					this.SendPropertyChanged("PhieuNhap");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MatHang_CTPhieuXuat", Storage="_MatHang", ThisKey="MaMH", OtherKey="MaMH", IsForeignKey=true)]
		public MatHang MatHang
		{
			get
			{
				return this._MatHang.Entity;
			}
			set
			{
				MatHang previousValue = this._MatHang.Entity;
				if (((previousValue != value) 
							|| (this._MatHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MatHang.Entity = null;
						previousValue.CTPhieuXuats.Remove(this);
					}
					this._MatHang.Entity = value;
					if ((value != null))
					{
						value.CTPhieuXuats.Add(this);
						this._MaMH = value.MaMH;
					}
					else
					{
						this._MaMH = default(string);
					}
					this.SendPropertyChanged("MatHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Dangnhap")]
	public partial class Dangnhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TaiKhoan;
		
		private string _MatKhau;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    #endregion
		
		public Dangnhap()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kho")]
	public partial class Kho : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MSKHO;
		
		private string _TenKho;
		
		private string _MDD;
		
		private string _DiaChi;
		
		private string _MaNVPhuTrach;
		
		private int _SDT;
		
		private string _LoaiHang;
		
		private EntitySet<PhieuNhap> _PhieuNhaps;
		
		private EntitySet<PhieuXuat> _PhieuXuats;
		
		private EntitySet<MatHang> _MatHangs;
		
		private EntityRef<DiaDiem> _DiaDiem;
		
		private EntityRef<LoaiHang> _LoaiHang1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMSKHOChanging(string value);
    partial void OnMSKHOChanged();
    partial void OnTenKhoChanging(string value);
    partial void OnTenKhoChanged();
    partial void OnMDDChanging(string value);
    partial void OnMDDChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnMaNVPhuTrachChanging(string value);
    partial void OnMaNVPhuTrachChanged();
    partial void OnSDTChanging(int value);
    partial void OnSDTChanged();
    partial void OnLoaiHangChanging(string value);
    partial void OnLoaiHangChanged();
    #endregion
		
		public Kho()
		{
			this._PhieuNhaps = new EntitySet<PhieuNhap>(new Action<PhieuNhap>(this.attach_PhieuNhaps), new Action<PhieuNhap>(this.detach_PhieuNhaps));
			this._PhieuXuats = new EntitySet<PhieuXuat>(new Action<PhieuXuat>(this.attach_PhieuXuats), new Action<PhieuXuat>(this.detach_PhieuXuats));
			this._MatHangs = new EntitySet<MatHang>(new Action<MatHang>(this.attach_MatHangs), new Action<MatHang>(this.detach_MatHangs));
			this._DiaDiem = default(EntityRef<DiaDiem>);
			this._LoaiHang1 = default(EntityRef<LoaiHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSKHO", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MSKHO
		{
			get
			{
				return this._MSKHO;
			}
			set
			{
				if ((this._MSKHO != value))
				{
					this.OnMSKHOChanging(value);
					this.SendPropertyChanging();
					this._MSKHO = value;
					this.SendPropertyChanged("MSKHO");
					this.OnMSKHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKho", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string TenKho
		{
			get
			{
				return this._TenKho;
			}
			set
			{
				if ((this._TenKho != value))
				{
					this.OnTenKhoChanging(value);
					this.SendPropertyChanging();
					this._TenKho = value;
					this.SendPropertyChanged("TenKho");
					this.OnTenKhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MDD", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MDD
		{
			get
			{
				return this._MDD;
			}
			set
			{
				if ((this._MDD != value))
				{
					if (this._DiaDiem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMDDChanging(value);
					this.SendPropertyChanging();
					this._MDD = value;
					this.SendPropertyChanged("MDD");
					this.OnMDDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNVPhuTrach", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string MaNVPhuTrach
		{
			get
			{
				return this._MaNVPhuTrach;
			}
			set
			{
				if ((this._MaNVPhuTrach != value))
				{
					this.OnMaNVPhuTrachChanging(value);
					this.SendPropertyChanging();
					this._MaNVPhuTrach = value;
					this.SendPropertyChanged("MaNVPhuTrach");
					this.OnMaNVPhuTrachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Int NOT NULL")]
		public int SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiHang", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string LoaiHang
		{
			get
			{
				return this._LoaiHang;
			}
			set
			{
				if ((this._LoaiHang != value))
				{
					if (this._LoaiHang1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLoaiHangChanging(value);
					this.SendPropertyChanging();
					this._LoaiHang = value;
					this.SendPropertyChanged("LoaiHang");
					this.OnLoaiHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kho_PhieuNhap", Storage="_PhieuNhaps", ThisKey="MSKHO", OtherKey="Kho")]
		public EntitySet<PhieuNhap> PhieuNhaps
		{
			get
			{
				return this._PhieuNhaps;
			}
			set
			{
				this._PhieuNhaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kho_PhieuXuat", Storage="_PhieuXuats", ThisKey="MSKHO", OtherKey="Kho")]
		public EntitySet<PhieuXuat> PhieuXuats
		{
			get
			{
				return this._PhieuXuats;
			}
			set
			{
				this._PhieuXuats.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kho_MatHang", Storage="_MatHangs", ThisKey="MSKHO", OtherKey="Kho")]
		public EntitySet<MatHang> MatHangs
		{
			get
			{
				return this._MatHangs;
			}
			set
			{
				this._MatHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiaDiem_Kho", Storage="_DiaDiem", ThisKey="MDD", OtherKey="MDD", IsForeignKey=true)]
		public DiaDiem DiaDiem
		{
			get
			{
				return this._DiaDiem.Entity;
			}
			set
			{
				DiaDiem previousValue = this._DiaDiem.Entity;
				if (((previousValue != value) 
							|| (this._DiaDiem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DiaDiem.Entity = null;
						previousValue.Khos.Remove(this);
					}
					this._DiaDiem.Entity = value;
					if ((value != null))
					{
						value.Khos.Add(this);
						this._MDD = value.MDD;
					}
					else
					{
						this._MDD = default(string);
					}
					this.SendPropertyChanged("DiaDiem");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiHang_Kho", Storage="_LoaiHang1", ThisKey="LoaiHang", OtherKey="MSLH", IsForeignKey=true)]
		public LoaiHang LoaiHang1
		{
			get
			{
				return this._LoaiHang1.Entity;
			}
			set
			{
				LoaiHang previousValue = this._LoaiHang1.Entity;
				if (((previousValue != value) 
							|| (this._LoaiHang1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiHang1.Entity = null;
						previousValue.Khos.Remove(this);
					}
					this._LoaiHang1.Entity = value;
					if ((value != null))
					{
						value.Khos.Add(this);
						this._LoaiHang = value.MSLH;
					}
					else
					{
						this._LoaiHang = default(string);
					}
					this.SendPropertyChanged("LoaiHang1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhieuNhaps(PhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.Kho1 = this;
		}
		
		private void detach_PhieuNhaps(PhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.Kho1 = null;
		}
		
		private void attach_PhieuXuats(PhieuXuat entity)
		{
			this.SendPropertyChanging();
			entity.Kho1 = this;
		}
		
		private void detach_PhieuXuats(PhieuXuat entity)
		{
			this.SendPropertyChanging();
			entity.Kho1 = null;
		}
		
		private void attach_MatHangs(MatHang entity)
		{
			this.SendPropertyChanging();
			entity.Kho1 = this;
		}
		
		private void detach_MatHangs(MatHang entity)
		{
			this.SendPropertyChanging();
			entity.Kho1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DiaDiem")]
	public partial class DiaDiem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MDD;
		
		private string _Ten;
		
		private int _SoLuongKho;
		
		private EntitySet<Kho> _Khos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMDDChanging(string value);
    partial void OnMDDChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnSoLuongKhoChanging(int value);
    partial void OnSoLuongKhoChanged();
    #endregion
		
		public DiaDiem()
		{
			this._Khos = new EntitySet<Kho>(new Action<Kho>(this.attach_Khos), new Action<Kho>(this.detach_Khos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MDD", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MDD
		{
			get
			{
				return this._MDD;
			}
			set
			{
				if ((this._MDD != value))
				{
					this.OnMDDChanging(value);
					this.SendPropertyChanging();
					this._MDD = value;
					this.SendPropertyChanged("MDD");
					this.OnMDDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongKho", DbType="Int NOT NULL")]
		public int SoLuongKho
		{
			get
			{
				return this._SoLuongKho;
			}
			set
			{
				if ((this._SoLuongKho != value))
				{
					this.OnSoLuongKhoChanging(value);
					this.SendPropertyChanging();
					this._SoLuongKho = value;
					this.SendPropertyChanged("SoLuongKho");
					this.OnSoLuongKhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiaDiem_Kho", Storage="_Khos", ThisKey="MDD", OtherKey="MDD")]
		public EntitySet<Kho> Khos
		{
			get
			{
				return this._Khos;
			}
			set
			{
				this._Khos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Khos(Kho entity)
		{
			this.SendPropertyChanging();
			entity.DiaDiem = this;
		}
		
		private void detach_Khos(Kho entity)
		{
			this.SendPropertyChanging();
			entity.DiaDiem = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiHang")]
	public partial class LoaiHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MSLH;
		
		private string _TenLH;
		
		private int _SoLuongMH;
		
		private EntitySet<CTPhieuNhap> _CTPhieuNhaps;
		
		private EntitySet<CTPhieuXuat> _CTPhieuXuats;
		
		private EntitySet<Kho> _Khos;
		
		private EntitySet<MatHang> _MatHangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMSLHChanging(string value);
    partial void OnMSLHChanged();
    partial void OnTenLHChanging(string value);
    partial void OnTenLHChanged();
    partial void OnSoLuongMHChanging(int value);
    partial void OnSoLuongMHChanged();
    #endregion
		
		public LoaiHang()
		{
			this._CTPhieuNhaps = new EntitySet<CTPhieuNhap>(new Action<CTPhieuNhap>(this.attach_CTPhieuNhaps), new Action<CTPhieuNhap>(this.detach_CTPhieuNhaps));
			this._CTPhieuXuats = new EntitySet<CTPhieuXuat>(new Action<CTPhieuXuat>(this.attach_CTPhieuXuats), new Action<CTPhieuXuat>(this.detach_CTPhieuXuats));
			this._Khos = new EntitySet<Kho>(new Action<Kho>(this.attach_Khos), new Action<Kho>(this.detach_Khos));
			this._MatHangs = new EntitySet<MatHang>(new Action<MatHang>(this.attach_MatHangs), new Action<MatHang>(this.detach_MatHangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSLH", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MSLH
		{
			get
			{
				return this._MSLH;
			}
			set
			{
				if ((this._MSLH != value))
				{
					this.OnMSLHChanging(value);
					this.SendPropertyChanging();
					this._MSLH = value;
					this.SendPropertyChanged("MSLH");
					this.OnMSLHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLH", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenLH
		{
			get
			{
				return this._TenLH;
			}
			set
			{
				if ((this._TenLH != value))
				{
					this.OnTenLHChanging(value);
					this.SendPropertyChanging();
					this._TenLH = value;
					this.SendPropertyChanged("TenLH");
					this.OnTenLHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongMH", DbType="Int NOT NULL")]
		public int SoLuongMH
		{
			get
			{
				return this._SoLuongMH;
			}
			set
			{
				if ((this._SoLuongMH != value))
				{
					this.OnSoLuongMHChanging(value);
					this.SendPropertyChanging();
					this._SoLuongMH = value;
					this.SendPropertyChanged("SoLuongMH");
					this.OnSoLuongMHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiHang_CTPhieuNhap", Storage="_CTPhieuNhaps", ThisKey="MSLH", OtherKey="LoaiHang")]
		public EntitySet<CTPhieuNhap> CTPhieuNhaps
		{
			get
			{
				return this._CTPhieuNhaps;
			}
			set
			{
				this._CTPhieuNhaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiHang_CTPhieuXuat", Storage="_CTPhieuXuats", ThisKey="MSLH", OtherKey="LoaiHang")]
		public EntitySet<CTPhieuXuat> CTPhieuXuats
		{
			get
			{
				return this._CTPhieuXuats;
			}
			set
			{
				this._CTPhieuXuats.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiHang_Kho", Storage="_Khos", ThisKey="MSLH", OtherKey="LoaiHang")]
		public EntitySet<Kho> Khos
		{
			get
			{
				return this._Khos;
			}
			set
			{
				this._Khos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiHang_MatHang", Storage="_MatHangs", ThisKey="MSLH", OtherKey="LoaiHang")]
		public EntitySet<MatHang> MatHangs
		{
			get
			{
				return this._MatHangs;
			}
			set
			{
				this._MatHangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTPhieuNhaps(CTPhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.LoaiHang1 = this;
		}
		
		private void detach_CTPhieuNhaps(CTPhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.LoaiHang1 = null;
		}
		
		private void attach_CTPhieuXuats(CTPhieuXuat entity)
		{
			this.SendPropertyChanging();
			entity.LoaiHang1 = this;
		}
		
		private void detach_CTPhieuXuats(CTPhieuXuat entity)
		{
			this.SendPropertyChanging();
			entity.LoaiHang1 = null;
		}
		
		private void attach_Khos(Kho entity)
		{
			this.SendPropertyChanging();
			entity.LoaiHang1 = this;
		}
		
		private void detach_Khos(Kho entity)
		{
			this.SendPropertyChanging();
			entity.LoaiHang1 = null;
		}
		
		private void attach_MatHangs(MatHang entity)
		{
			this.SendPropertyChanging();
			entity.LoaiHang1 = this;
		}
		
		private void detach_MatHangs(MatHang entity)
		{
			this.SendPropertyChanging();
			entity.LoaiHang1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhieuNhap")]
	public partial class PhieuNhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SOPN;
		
		private System.DateTime _NgayLapPhieu;
		
		private string _Kho;
		
		private string _MSNV;
		
		private EntitySet<CTPhieuNhap> _CTPhieuNhaps;
		
		private EntitySet<CTPhieuXuat> _CTPhieuXuats;
		
		private EntityRef<Kho> _Kho1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSOPNChanging(string value);
    partial void OnSOPNChanged();
    partial void OnNgayLapPhieuChanging(System.DateTime value);
    partial void OnNgayLapPhieuChanged();
    partial void OnKhoChanging(string value);
    partial void OnKhoChanged();
    partial void OnMSNVChanging(string value);
    partial void OnMSNVChanged();
    #endregion
		
		public PhieuNhap()
		{
			this._CTPhieuNhaps = new EntitySet<CTPhieuNhap>(new Action<CTPhieuNhap>(this.attach_CTPhieuNhaps), new Action<CTPhieuNhap>(this.detach_CTPhieuNhaps));
			this._CTPhieuXuats = new EntitySet<CTPhieuXuat>(new Action<CTPhieuXuat>(this.attach_CTPhieuXuats), new Action<CTPhieuXuat>(this.detach_CTPhieuXuats));
			this._Kho1 = default(EntityRef<Kho>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOPN", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SOPN
		{
			get
			{
				return this._SOPN;
			}
			set
			{
				if ((this._SOPN != value))
				{
					this.OnSOPNChanging(value);
					this.SendPropertyChanging();
					this._SOPN = value;
					this.SendPropertyChanged("SOPN");
					this.OnSOPNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLapPhieu", DbType="DateTime NOT NULL")]
		public System.DateTime NgayLapPhieu
		{
			get
			{
				return this._NgayLapPhieu;
			}
			set
			{
				if ((this._NgayLapPhieu != value))
				{
					this.OnNgayLapPhieuChanging(value);
					this.SendPropertyChanging();
					this._NgayLapPhieu = value;
					this.SendPropertyChanged("NgayLapPhieu");
					this.OnNgayLapPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kho", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Kho
		{
			get
			{
				return this._Kho;
			}
			set
			{
				if ((this._Kho != value))
				{
					if (this._Kho1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKhoChanging(value);
					this.SendPropertyChanging();
					this._Kho = value;
					this.SendPropertyChanged("Kho");
					this.OnKhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSNV", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string MSNV
		{
			get
			{
				return this._MSNV;
			}
			set
			{
				if ((this._MSNV != value))
				{
					this.OnMSNVChanging(value);
					this.SendPropertyChanging();
					this._MSNV = value;
					this.SendPropertyChanged("MSNV");
					this.OnMSNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuNhap_CTPhieuNhap", Storage="_CTPhieuNhaps", ThisKey="SOPN", OtherKey="SOPN")]
		public EntitySet<CTPhieuNhap> CTPhieuNhaps
		{
			get
			{
				return this._CTPhieuNhaps;
			}
			set
			{
				this._CTPhieuNhaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuNhap_CTPhieuXuat", Storage="_CTPhieuXuats", ThisKey="SOPN", OtherKey="SOPX")]
		public EntitySet<CTPhieuXuat> CTPhieuXuats
		{
			get
			{
				return this._CTPhieuXuats;
			}
			set
			{
				this._CTPhieuXuats.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kho_PhieuNhap", Storage="_Kho1", ThisKey="Kho", OtherKey="MSKHO", IsForeignKey=true)]
		public Kho Kho1
		{
			get
			{
				return this._Kho1.Entity;
			}
			set
			{
				Kho previousValue = this._Kho1.Entity;
				if (((previousValue != value) 
							|| (this._Kho1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kho1.Entity = null;
						previousValue.PhieuNhaps.Remove(this);
					}
					this._Kho1.Entity = value;
					if ((value != null))
					{
						value.PhieuNhaps.Add(this);
						this._Kho = value.MSKHO;
					}
					else
					{
						this._Kho = default(string);
					}
					this.SendPropertyChanged("Kho1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTPhieuNhaps(CTPhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.PhieuNhap = this;
		}
		
		private void detach_CTPhieuNhaps(CTPhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.PhieuNhap = null;
		}
		
		private void attach_CTPhieuXuats(CTPhieuXuat entity)
		{
			this.SendPropertyChanging();
			entity.PhieuNhap = this;
		}
		
		private void detach_CTPhieuXuats(CTPhieuXuat entity)
		{
			this.SendPropertyChanging();
			entity.PhieuNhap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhieuXuat")]
	public partial class PhieuXuat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SOPX;
		
		private System.DateTime _NgayLapPhieu;
		
		private string _Kho;
		
		private string _MSNV;
		
		private EntityRef<Kho> _Kho1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSOPXChanging(string value);
    partial void OnSOPXChanged();
    partial void OnNgayLapPhieuChanging(System.DateTime value);
    partial void OnNgayLapPhieuChanged();
    partial void OnKhoChanging(string value);
    partial void OnKhoChanged();
    partial void OnMSNVChanging(string value);
    partial void OnMSNVChanged();
    #endregion
		
		public PhieuXuat()
		{
			this._Kho1 = default(EntityRef<Kho>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOPX", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SOPX
		{
			get
			{
				return this._SOPX;
			}
			set
			{
				if ((this._SOPX != value))
				{
					this.OnSOPXChanging(value);
					this.SendPropertyChanging();
					this._SOPX = value;
					this.SendPropertyChanged("SOPX");
					this.OnSOPXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLapPhieu", DbType="DateTime NOT NULL")]
		public System.DateTime NgayLapPhieu
		{
			get
			{
				return this._NgayLapPhieu;
			}
			set
			{
				if ((this._NgayLapPhieu != value))
				{
					this.OnNgayLapPhieuChanging(value);
					this.SendPropertyChanging();
					this._NgayLapPhieu = value;
					this.SendPropertyChanged("NgayLapPhieu");
					this.OnNgayLapPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kho", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Kho
		{
			get
			{
				return this._Kho;
			}
			set
			{
				if ((this._Kho != value))
				{
					if (this._Kho1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKhoChanging(value);
					this.SendPropertyChanging();
					this._Kho = value;
					this.SendPropertyChanged("Kho");
					this.OnKhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSNV", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string MSNV
		{
			get
			{
				return this._MSNV;
			}
			set
			{
				if ((this._MSNV != value))
				{
					this.OnMSNVChanging(value);
					this.SendPropertyChanging();
					this._MSNV = value;
					this.SendPropertyChanged("MSNV");
					this.OnMSNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kho_PhieuXuat", Storage="_Kho1", ThisKey="Kho", OtherKey="MSKHO", IsForeignKey=true)]
		public Kho Kho1
		{
			get
			{
				return this._Kho1.Entity;
			}
			set
			{
				Kho previousValue = this._Kho1.Entity;
				if (((previousValue != value) 
							|| (this._Kho1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kho1.Entity = null;
						previousValue.PhieuXuats.Remove(this);
					}
					this._Kho1.Entity = value;
					if ((value != null))
					{
						value.PhieuXuats.Add(this);
						this._Kho = value.MSKHO;
					}
					else
					{
						this._Kho = default(string);
					}
					this.SendPropertyChanged("Kho1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MatHang")]
	public partial class MatHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaMH;
		
		private string _TenMH;
		
		private string _LoaiHang;
		
		private string _Kho;
		
		private int _DonGia;
		
		private int _SoLuong;
		
		private EntitySet<CTPhieuNhap> _CTPhieuNhaps;
		
		private EntitySet<CTPhieuXuat> _CTPhieuXuats;
		
		private EntityRef<Kho> _Kho1;
		
		private EntityRef<LoaiHang> _LoaiHang1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaMHChanging(string value);
    partial void OnMaMHChanged();
    partial void OnTenMHChanging(string value);
    partial void OnTenMHChanged();
    partial void OnLoaiHangChanging(string value);
    partial void OnLoaiHangChanged();
    partial void OnKhoChanging(string value);
    partial void OnKhoChanged();
    partial void OnDonGiaChanging(int value);
    partial void OnDonGiaChanged();
    partial void OnSoLuongChanging(int value);
    partial void OnSoLuongChanged();
    #endregion
		
		public MatHang()
		{
			this._CTPhieuNhaps = new EntitySet<CTPhieuNhap>(new Action<CTPhieuNhap>(this.attach_CTPhieuNhaps), new Action<CTPhieuNhap>(this.detach_CTPhieuNhaps));
			this._CTPhieuXuats = new EntitySet<CTPhieuXuat>(new Action<CTPhieuXuat>(this.attach_CTPhieuXuats), new Action<CTPhieuXuat>(this.detach_CTPhieuXuats));
			this._Kho1 = default(EntityRef<Kho>);
			this._LoaiHang1 = default(EntityRef<LoaiHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMH", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaMH
		{
			get
			{
				return this._MaMH;
			}
			set
			{
				if ((this._MaMH != value))
				{
					this.OnMaMHChanging(value);
					this.SendPropertyChanging();
					this._MaMH = value;
					this.SendPropertyChanged("MaMH");
					this.OnMaMHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMH", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenMH
		{
			get
			{
				return this._TenMH;
			}
			set
			{
				if ((this._TenMH != value))
				{
					this.OnTenMHChanging(value);
					this.SendPropertyChanging();
					this._TenMH = value;
					this.SendPropertyChanged("TenMH");
					this.OnTenMHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiHang", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string LoaiHang
		{
			get
			{
				return this._LoaiHang;
			}
			set
			{
				if ((this._LoaiHang != value))
				{
					if (this._LoaiHang1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLoaiHangChanging(value);
					this.SendPropertyChanging();
					this._LoaiHang = value;
					this.SendPropertyChanged("LoaiHang");
					this.OnLoaiHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kho", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Kho
		{
			get
			{
				return this._Kho;
			}
			set
			{
				if ((this._Kho != value))
				{
					if (this._Kho1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKhoChanging(value);
					this.SendPropertyChanging();
					this._Kho = value;
					this.SendPropertyChanged("Kho");
					this.OnKhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Int NOT NULL")]
		public int DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int NOT NULL")]
		public int SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MatHang_CTPhieuNhap", Storage="_CTPhieuNhaps", ThisKey="MaMH", OtherKey="MaMH")]
		public EntitySet<CTPhieuNhap> CTPhieuNhaps
		{
			get
			{
				return this._CTPhieuNhaps;
			}
			set
			{
				this._CTPhieuNhaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MatHang_CTPhieuXuat", Storage="_CTPhieuXuats", ThisKey="MaMH", OtherKey="MaMH")]
		public EntitySet<CTPhieuXuat> CTPhieuXuats
		{
			get
			{
				return this._CTPhieuXuats;
			}
			set
			{
				this._CTPhieuXuats.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kho_MatHang", Storage="_Kho1", ThisKey="Kho", OtherKey="MSKHO", IsForeignKey=true)]
		public Kho Kho1
		{
			get
			{
				return this._Kho1.Entity;
			}
			set
			{
				Kho previousValue = this._Kho1.Entity;
				if (((previousValue != value) 
							|| (this._Kho1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kho1.Entity = null;
						previousValue.MatHangs.Remove(this);
					}
					this._Kho1.Entity = value;
					if ((value != null))
					{
						value.MatHangs.Add(this);
						this._Kho = value.MSKHO;
					}
					else
					{
						this._Kho = default(string);
					}
					this.SendPropertyChanged("Kho1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiHang_MatHang", Storage="_LoaiHang1", ThisKey="LoaiHang", OtherKey="MSLH", IsForeignKey=true)]
		public LoaiHang LoaiHang1
		{
			get
			{
				return this._LoaiHang1.Entity;
			}
			set
			{
				LoaiHang previousValue = this._LoaiHang1.Entity;
				if (((previousValue != value) 
							|| (this._LoaiHang1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiHang1.Entity = null;
						previousValue.MatHangs.Remove(this);
					}
					this._LoaiHang1.Entity = value;
					if ((value != null))
					{
						value.MatHangs.Add(this);
						this._LoaiHang = value.MSLH;
					}
					else
					{
						this._LoaiHang = default(string);
					}
					this.SendPropertyChanged("LoaiHang1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTPhieuNhaps(CTPhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.MatHang = this;
		}
		
		private void detach_CTPhieuNhaps(CTPhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.MatHang = null;
		}
		
		private void attach_CTPhieuXuats(CTPhieuXuat entity)
		{
			this.SendPropertyChanging();
			entity.MatHang = this;
		}
		
		private void detach_CTPhieuXuats(CTPhieuXuat entity)
		{
			this.SendPropertyChanging();
			entity.MatHang = null;
		}
	}
}
#pragma warning restore 1591
